### ISSUE TITLE
Failing to migrate LXD

### ISSUE THREAD

**Issue by Saviq** [samuelmeuli/action-snapcraft#30]
I've seen this happen somewhat frequently these past weeks:
```plain
Installing Snapcraft for Linux…
snapcraft 4.5.4 from Canonical* installed
snap "lxd" is already installed, see 'snap help refresh'
=> Connecting to source server
error: Unable to connect to the source LXD: Get "http://unix.socket/1.0": dial unix /var/lib/lxd/unix.socket: connect: no such file or directory
child_process.js:660
    throw err;
    ^

Error: Command failed: sudo /snap/bin/lxd.migrate -yes
    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at run (/home/runner/work/_actions/samuelmeuli/action-snapcraft/v1/index.js:15:2)
    at runLinuxInstaller (/home/runner/work/_actions/samuelmeuli/action-snapcraft/v1/index.js:44:3)
    at runAction (/home/runner/work/_actions/samuelmeuli/action-snapcraft/v1/index.js:71:3)
    at Object.<anonymous> (/home/runner/work/_actions/samuelmeuli/action-snapcraft/v1/index.js:95:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 2218,
  stdout: null,
  stderr: null
}
```

Do you think the migration could be made optional? Most often this action is going to run when LXD is empty anyway?

**Comment by AlanGriffiths** [comment]
I've also seen this today.

**Comment by roboticsai** [comment]
Me too when using ubuntu-latest or ubuntu-20.04. Has anyone solved this?

**Comment by Saviq** [comment]
> Me too when using ubuntu-latest or ubuntu-20.04. Has anyone solved this?

@roboticsai I've been using this action instead: https://github.com/whywaita/setup-lxd
