### ISSUE TITLE
Command failed: /snap/bin/snapcraft login --with ./snap-token.txt

### ISSUE THREAD

**Issue by linonetwo** [samuelmeuli/action-snapcraft#32]
Run samuelmeuli/action-snapcraft@v1
  with:
    snapcraft_token: ***
    channel: stable

Installing Snapcraft for Linux…
snapcraft 4.8.3 from Canonical* installed

Snapcraft is installed at /snap/bin/snapcraft

Logging in to Snapcraft…
Error fetching account information from store: The request is missing an Authorization header field containing a valid macaroon
child_process.js:660
    throw err;
    ^

Error: Command failed: /snap/bin/snapcraft login --with ./snap-token.txt
    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at run (/home/runner/work/_actions/samuelmeuli/action-snapcraft/v1/index.js:15:2)
    at runAction (/home/runner/work/_actions/samuelmeuli/action-snapcraft/v1/index.js:88:3)
    at Object.<anonymous> (/home/runner/work/_actions/samuelmeuli/action-snapcraft/v1/index.js:95:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  status: 2,
  signal: null,
  output: [ null, null, null ],
  pid: 1689,
  stdout: null,
  stderr: null
}

**Comment by incu6us** [comment]
I've fixed it with updated token:
```
snapcraft export-login --snaps <snap> --channels stable,edge,candidate,beta -
```
