### ISSUE TITLE
Error fetching account information from store: The request is missing an Authorization header field containing a valid macaroon

### ISSUE THREAD

**Issue by kdheepak** [samuelmeuli/action-snapcraft#33]
Thanks for making this action. I've been using this for almost a year now and it has been working great! But now I'm getting the following error when I use this now: 

```
Run samuelmeuli/action-snapcraft@v1
  with:
    use_lxd: true
    snapcraft_token: ***
    channel: stable

Installing Snapcraft for Linux…
2021-10-27T21:15:27Z INFO Waiting for automatic snapd restart...
snapcraft 5.0 from Canonical* installed
lxd 4.19 from Canonical* installed
=> Connecting to source server
=> Connecting to destination server
=> Running sanity checks
The source server is empty, no migration needed.

The migration is now complete and your containers should be back online.

All done. You may need to close your current shell and open a new one to have the "lxc" command work.
To migrate your existing client configuration, move ~/.config/lxc to ~/snap/lxd/common/config

Snapcraft is installed at /snap/bin/snapcraft

Logging in to Snapcraft…
Error fetching account information from store: The request is missing an Authorization header field containing a valid macaroon
child_process.js:660
    throw err;
    ^

Error: Command failed: /snap/bin/snapcraft login --with ./snap-token.txt
    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at run (/home/runner/work/_actions/samuelmeuli/action-snapcraft/v1/index.js:15:2)
    at runAction (/home/runner/work/_actions/samuelmeuli/action-snapcraft/v1/index.js:88:3)
    at Object.<anonymous> (/home/runner/work/_actions/samuelmeuli/action-snapcraft/v1/index.js:95:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  status: 2,
  signal: null,
  output: [ null, null, null ],
  pid: 5644,
  stdout: null,
  stderr: null
}
```

This was working a month ago, so I'm not sure what is going on.

**Comment by casperdcl** [comment]
Your snapcraft token probably expired and needs to be regenerated :)

See #32

**Comment by kdheepak** [comment]
Omg you are right, that's so embarrassing. It expired exactly on Oct 27th.
