### ISSUE TITLE
"Unable to connect to the source LXD" on latest-ubuntu

### ISSUE THREAD

**Issue by shahidghafoor00** [samuelmeuli/action-snapcraft#35]
error: Unable to connect to the source LXD: Get "http://unix.socket/1.0": dial unix /var/lib/lxd/unix.socket: connect: no such file or directory

**Comment by abulka** [comment]
Yeah I'm getting this too

```
Run samuelmeuli/action-snapcraft@master

Installing Snapcraft for Linux…
snapcraft [7](https://github.com/abulka/pynsource/actions/runs/4249226115/jobs/7389169101#step:3:8).2.9 from Canonical** installed
snap "lxd" is already installed, see 'snap help refresh'
=> Connecting to source server
error: Unable to connect to the source LXD: Get "http://unix.socket/1.0": dial unix /var/lib/lxd/unix.socket: connect: no such file or directory
node:child_process:902
    throw err;
    ^

Error: Command failed: sudo /snap/bin/lxd.migrate -yes
    at checkExecSyncError (node:child_process:[8](https://github.com/abulka/pynsource/actions/runs/4249226115/jobs/7389169101#step:3:9)28:11)
    at execSync (node:child_process:8[9](https://github.com/abulka/pynsource/actions/runs/4249226115/jobs/7389169101#step:3:10)9:15)
    at run (/home/runner/work/_actions/samuelmeuli/action-snapcraft/master/index.js:15:2)
    at runLinuxInstaller (/home/runner/work/_actions/samuelmeuli/action-snapcraft/master/index.js:44:3)
    at runAction (/home/runner/work/_actions/samuelmeuli/action-snapcraft/master/index.js:71:3)
    at Object.<anonymous> (/home/runner/work/_actions/samuelmeuli/action-snapcraft/master/index.js:95:1)
    at Module._compile (node:internal/modules/cjs/loader:1[10](https://github.com/abulka/pynsource/actions/runs/4249226115/jobs/7389169101#step:3:11)5:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:[11](https://github.com/abulka/pynsource/actions/runs/4249226115/jobs/7389169101#step:3:12)59:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 18[17](https://github.com/abulka/pynsource/actions/runs/4249226115/jobs/7389169101#step:3:18),
  stdout: null,
  stderr: null
}
```

my github actions step is

```yaml
      - name: Install Snapcraft, LXD and set Auth
        uses: samuelmeuli/action-snapcraft@master
        with:
          use_lxd: true
          snapcraft_token: ${{ secrets.snapcraft_token }}
```

**Comment by abulka** [comment]
I have discovered and switched to using the official GitHub action for building with snapcraft https://github.com/snapcore/action-build which works perfectly and seems to be better maintained and documented.
