### ISSUE TITLE
Snapcraft binary not found

### ISSUE THREAD

**Issue by TorstenDittmann** [samuelmeuli/action-snapcraft#8]
For some reason the snapcraft action stopped working for me. It was not touched and worked before.

```
Installing Snapcraft for Linux…
snapcraft 3.11 from Canonical* installed

Logging in to Snapcraft…
/bin/sh: 1: snapcraft: not found
child_process.js:660
    throw err;
    ^

Error: Command failed: snapcraft login --with ./snap-token.txt
    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at run (/home/runner/work/_actions/samuelmeuli/action-snapcraft/v1.1.0/index.js:14:20)
    at runAction (/home/runner/work/_actions/samuelmeuli/action-snapcraft/v1.1.0/index.js:80:3)
    at Object.<anonymous> (/home/runner/work/_actions/samuelmeuli/action-snapcraft/v1.1.0/index.js:87:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  status: 127,
  signal: null,
  output: [ null, null, null ],
  pid: 2803,
  stdout: null,
  stderr: null
}
```
### Full log
https://github.com/TorstenDittmann/OmniaWrite/runs/597951550?check_suite_focus=true

### Used action
https://github.com/TorstenDittmann/OmniaWrite/blob/master/.github/workflows/build.yml#L21-L25

Seems like, using it on macOS works fine.

**Comment by baruchiro** [comment]
#MeToo

**Comment by samuelmeuli** [comment]
It looks like the Ubuntu VMs no longer have `/snap/bin` in `$PATH`, resulting in the `snapcraft` binary not being found anymore.

The next release should fix this.
